### PR TITLE
Simplify creation of dates.txt

### PR DESCRIPTION
**Pull request by BenBE**
Attached some script to build custom paintings by noting down the days per week that should be marked.

Regenerate `dates.txt` by running `./dates.sh 2019-07-14 < dow.txt > dates.txt`.

You could even do something like:
`./dates.sh 'today -42 weeks' < dow.txt > dates.txt`
Which would roughly align so the latest commit is at the end of this week.

I'd need to check if a `LANG=C LC_ALL=C` is necessary for `date` arithmetic to work properly. In case of doubt it doesn't hurt.

### CODE REVIEW

**Comment by rossabaker** [comment]
This is good. 'today -47 weeks' centers it nicely, and I suppose '-42 weeks' lets one set it and forget it for a couple months as it scrolls left.

Is there any reason not to just integrate dates.sh into the paint script?  Otherwise, we'll need to regenerate the dates.txt periodically so it works out of the box.

Something is making mine fade: mine looked crisp after I pushed, and then when I check back a few minutes later, it finds an extra 100 or 180 commits to that repo in the "E", and the earlier letters turn a lighter green.  I think it's unrelated to this PR, but I didn't notice until I ran from this branch.  I'm curious if this is happening to anyone else.

**Comment by BenBE** [comment]
No particular reason, just didn't want to mix those scripts together. If you like I can also build a mixed-together version; shouldn't be too hard.

**Comment by wolfwood** [comment]
since there is a 4 color palette available, I think keeping the last column in `dates.txt` is a good idea.

I'm working on rasterizing a given font in an .xcf with a 4 color indexed-palette, with the goal of producing 'anti-aliased' text.

I definitely agree that there should be a time-agnostic intermediate representation, and then a just-in-time conversion to a dates file.

**Comment by BenBE** [comment]
It's actually even five colors. That means: Even more fun … ;-)

AHHH, that explains the last column of the original `dates.txt`. I'll add it in and redo that commit so that the generated `dates.txt` includes the pixel color column again.

**Comment by BenBE** [comment]
Seems color levels are: `ceil(max/4*level)`, for me with 5 contributions max this gives:
```
0 -> 0
1 -> 1
2 -> 2,3
3 -> 4
4 -> 5
```
Please confirm. Based on that calculations for needed number of commits can be made.

**Comment by wolfwood** [comment]
@BenBE I wasn't counting the 0/grey color since those dates don't appear in the list at all (assuming maxCommits is set appropriately).

https://github.com/LindseyB/github-contribution-graph-art-generator asserts a minimum value for maxCommits at 4, and then has the following logic:

```
  var commitUnit = Math.ceil(maxCommits / 4);
  
  var color_map = [
    {color: "#c6e48b", commits: commitUnit},
    {color: "#7bc96f", commits: commitUnit * 2},
    {color: "#239a3b", commits: commitUnit * 3},
    {color: "#196127", commits: commitUnit * 4}
  ]
```

However, to force unlisted dates (which have at most maxCommits, preexisting) to be 0, the number of commits for a color 1-4 could be set to color*(maxCommits+1). this also requires that 4 appears somewhere in the image or the colors will be wrong.

This also has the property that successive runs (once we use your fix for #2 ) will render properly, as the max commits will keep scaling up. Obviously this is not ideal, and either deleting and recreating the branch or force pushing the parent of the graphiti commits is a 'more correct' approach.

**Comment by BenBE** [comment]
In the last commit I added while reworking the comments from earlier) I made the `paint.sh` script use the last column directly use the base unit for scaling. While you could randomly select any commit count between the lower and upper bounds for any color to cause that one, it is basically to noisy and unreliable to ensure the picture is as crisp as can be. With slight modifications to the command I posted in #2 you could even compensate for pre-existing commits per day, but that's nothing you want to implement in bash, except if you're looking for pain …

**Comment by lindsaylevine** [comment]
@BenBE @rossabaker hey yall totally bash-clueless here on osx 10.14.6

when i try to run ./dates.sh (with any arguments), including the examples in the PR description, i get:

Screen Shot 2020-08-17 at 4 36 22 AM

i tried LANG=C via https://blog.frd.mn/puzzling-with-os-xs-date/  and nothing seems to be working, any help? didn't wanna open an issue because i suspect it's just me being clueless

thanks!!

**Comment by wolfwood** [comment]
if you add `set -x` as the second line of the script, then it will print
the commands it is running. then we could see exactly what is failing.

it's possible that instead of LANG=C we need a locale that uses the ISO
date format being used?

**Comment by lindsaylevine** [comment]
`set -x` was always in there 🤔 (is in dates.sh in master)

Screen Shot 2020-08-17 at 12 12 34 PM

**Comment by wolfwood** [comment]
that's `set -e` which makes it stop in the first error `set -x` will echo
commands as they run

**Comment by lindsaylevine** [comment]
oof my bad!! here ya go
Screen Shot 2020-08-17 at 12 35 22 PM

**Comment by wolfwood** [comment]
Thanks, it looks like the OSX `date` command has different syntax. 

in the first case I think `date --date 2020-08-17 +%u`  should become `date 2020-08-17 +%u`

in the second case `date --date '2020-08-17 - 4 days' +%Y-%m-%d` should become `date -j -v-4d 2020-08-17+%Y-%m-%d` ?

@lindsaylevine can you run the following three commands and show us the output?
```
date --date 2020-08-17; echo $?
date 2020-08-17 +%u
date -j -v-4d 2020-08-17 +%Y-%m-%d
```

**Comment by wolfwood** [comment]
@lindsaylevine wait, I think -v might try to change your system time :roll_eyes: make the last command `date -j -v-4d 2020-08-17+%Y-%m-%d` instead, sorry.

**Comment by wolfwood** [comment]
https://www.shell-tips.com/linux/how-to-format-date-and-time-in-linux-macos-and-bash/#format-a-date-on-unix-macos-using-the-bsd-date-command-line

**Comment by lindsaylevine** [comment]
sorry for delay! 
Screen Shot 2020-08-17 at 11 26 16 PM

**Comment by wolfwood** [comment]
@lindsaylevine the first command 'worked', its exit code, in `$?`, indicates an error; so we will be able to detect the BSD version of the `date` command and make adjustments. for the rest it looks like we need to specify an input format as well as the output format.

can you try:
```
date -j -f %u 2020-08-17 +%u
date -j -v-4d -f %Y-%m-%d  2020-08-17 +%Y-%m-%d
```

**Comment by lindsaylevine** [comment]
Screen Shot 2020-08-19 at 5 20 02 PM

!!!!!!!!

assuming this is now what we want pls lmk how to update dates.sh !
(thanks so much btw)

**Comment by wolfwood** [comment]
this is good news! (tho i should have used `-f %Y-%m-%d` for the first command, same as the second)

I would like to write a small wrapper that can be `source`'d by both this script and my raster.sh to provide platform-agnostic date functions.  I'll open a separate issue for that i think.

it should be quick work, but if you'd like i can show you tomorrow what needs to be changed locally to get you unstuck.

**Comment by lindsaylevine** [comment]
saw the issue, thanks so much :)

**Pull request merged**
